CREATE OR REPLACE FUNCTION F_CONSULTADIRECCION(vregistro number ,vtipo number) RETURN RP_DIRECCION_TP AS 

cursor cudatos is select REGISTRO,TIPO_DIRECCION,MUNICIPIO,DIRECCION,TELEFONO,FAX,CORREO_ELECTRONICO,TELEFONO_CELULAR,TELEFONO3,APARTADO,BARRIO,SW_SMS,SW_LLAMADAS,ID_ZONA,ZONA_POSTAL,ID_SEDE_ADMINISTRATIVA,UBICACION_EMPRESA from rp_direccion where registro= vregistro and tipo_direccion = vtipo;




REGISTRO	NUMBER(10,0);
TIPO_DIRECCION	NUMBER(5,0);
MUNICIPIO	NUMBER(10,0);
DIRECCION	VARCHAR2(200 BYTE);
TELEFONO	VARCHAR2(30 BYTE);
FAX	VARCHAR2(10 BYTE);
CORREO_ELECTRONICO	VARCHAR2(50 BYTE);
TELEFONO_CELULAR	VARCHAR2(10 BYTE);
TELEFONO3	NUMBER(10,0);
APARTADO	NUMBER(10,0);
BARRIO	NUMBER(10,0);
SW_SMS	NUMBER(1,0);
SW_LLAMADAS	NUMBER;
ID_ZONA	NUMBER(1,0);
ZONA_POSTAL	NUMBER(6,0);
ID_SEDE_ADMINISTRATIVA	NUMBER(8,0);
UBICACION_EMPRESA	NUMBER(5,0);


BEGIN

  open cudatos;
  fetch cudatos into REGISTRO,TIPO_DIRECCION,MUNICIPIO,DIRECCION,TELEFONO,FAX,CORREO_ELECTRONICO,TELEFONO_CELULAR,TELEFONO3,APARTADO,BARRIO,SW_SMS,SW_LLAMADAS,ID_ZONA,ZONA_POSTAL,ID_SEDE_ADMINISTRATIVA,UBICACION_EMPRESA;
  close cudatos;
    
  return RP_DIRECCION_TP(REGISTRO,TIPO_DIRECCION,MUNICIPIO,DIRECCION,TELEFONO,FAX,CORREO_ELECTRONICO,TELEFONO_CELULAR,TELEFONO3,APARTADO,BARRIO,SW_SMS,SW_LLAMADAS,ID_ZONA,ZONA_POSTAL,ID_SEDE_ADMINISTRATIVA,UBICACION_EMPRESA);
  
END F_CONSULTADIRECCION;