CREATE SEQUENCE CD_JSON_GENERADO_SEQ INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE CD_TABLA_DATOS_JSON_SEQ INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE CD_JSON_LOG_ERRORES_CARGUE_SQ INCREMENT BY 1 START WITH 1;

