--------------------------------------------------------
-- Archivo creado  - viernes-diciembre-04-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CD_DETALLE_TABLA_JSON
--------------------------------------------------------
  CREATE TABLE "RECA_DB"."CD_DETALLE_TABLA_JSON" 
   (	"ID" NUMBER(15,0), 
	"ID_TABLA" NUMBER(15,0), 
	"NOMBRE_CAMPO_JSON" VARCHAR2(100 BYTE), 
	"NOMBRE_CAMPO_ORACLE" VARCHAR2(500 BYTE), 
	"TIPO_CAMPO" CHAR(1 BYTE), 
	"TIPODATO" VARCHAR2(50 BYTE), 
	"ORDEN" NUMBER(10,0), 
	"OBLIGATORIO" VARCHAR2(1 BYTE), 
	"NOMBRECAMPODESINO" VARCHAR2(100 BYTE), 
	"NOMBRETABLADESTINO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RECADATA" ;
 

   COMMENT ON COLUMN "RECA_DB"."CD_DETALLE_TABLA_JSON"."ID" IS 'id clave principal';
 
   COMMENT ON COLUMN "RECA_DB"."CD_DETALLE_TABLA_JSON"."ID_TABLA" IS 'id tabla estructura. ';
 
   COMMENT ON COLUMN "RECA_DB"."CD_DETALLE_TABLA_JSON"."NOMBRE_CAMPO_JSON" IS 'nombre campo json.';
 
   COMMENT ON COLUMN "RECA_DB"."CD_DETALLE_TABLA_JSON"."NOMBRE_CAMPO_ORACLE" IS 'nombre campo oracle.';
 
   COMMENT ON COLUMN "RECA_DB"."CD_DETALLE_TABLA_JSON"."TIPO_CAMPO" IS 'N normal , S Sublista.';
 
   COMMENT ON COLUMN "RECA_DB"."CD_DETALLE_TABLA_JSON"."ORDEN" IS 'Ordenamiento de tabla';
 
   COMMENT ON COLUMN "RECA_DB"."CD_DETALLE_TABLA_JSON"."OBLIGATORIO" IS 'Si el campo es obligatorio para cargue';
 
   COMMENT ON COLUMN "RECA_DB"."CD_DETALLE_TABLA_JSON"."NOMBRECAMPODESINO" IS 'Define en que campo de oracle destino';
 
   COMMENT ON COLUMN "RECA_DB"."CD_DETALLE_TABLA_JSON"."NOMBRETABLADESTINO" IS 'Define nombre tabla destino';
--------------------------------------------------------
--  DDL for Table CD_HOMOLOGACION_JSON
--------------------------------------------------------

  CREATE TABLE "RECA_DB"."CD_HOMOLOGACION_JSON" 
   (	"ID" NUMBER(15,0), 
	"TABLA" VARCHAR2(500 BYTE), 
	"VALOR_LOCAL" VARCHAR2(100 BYTE), 
	"VALOR_HOMOLOGADO" VARCHAR2(100 BYTE), 
	"DESCRIPCION_CAMPO" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RECADATA" ;
 

   COMMENT ON COLUMN "RECA_DB"."CD_HOMOLOGACION_JSON"."TABLA" IS 'Tabla de homologacion.
';
 
   COMMENT ON COLUMN "RECA_DB"."CD_HOMOLOGACION_JSON"."VALOR_LOCAL" IS 'Valor dato local';
--------------------------------------------------------
--  DDL for Table CD_JSON_CARGUE
--------------------------------------------------------

  CREATE TABLE "RECA_DB"."CD_JSON_CARGUE" 
   (	"ID" NUMBER(15,0), 
	"ID_MAESTRA_JSON" NUMBER(15,0), 
	"FECHA_CARGUE" DATE, 
	"ARCHIVO_JSON_CARGADO" VARCHAR2(100 BYTE), 
	"LOG" VARCHAR2(4000 BYTE), 
	"JSON_CARGADO" CLOB, 
	"NRO_PROPONENTE" NUMBER(10,0), 
	"MATRICULA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RECADATA" 
 LOB ("JSON_CARGADO") STORE AS BASICFILE (
  TABLESPACE "RECADATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
 

   COMMENT ON COLUMN "RECA_DB"."CD_JSON_CARGUE"."ID" IS 'id llave principal';
 
   COMMENT ON COLUMN "RECA_DB"."CD_JSON_CARGUE"."ID_MAESTRA_JSON" IS 'id maestra json.';
 
   COMMENT ON COLUMN "RECA_DB"."CD_JSON_CARGUE"."FECHA_CARGUE" IS 'Fecha cargue json.';
 
   COMMENT ON COLUMN "RECA_DB"."CD_JSON_CARGUE"."ARCHIVO_JSON_CARGADO" IS 'Nombre archivo cargado.';
 
   COMMENT ON COLUMN "RECA_DB"."CD_JSON_CARGUE"."LOG" IS 'Log de errores';
 
   COMMENT ON COLUMN "RECA_DB"."CD_JSON_CARGUE"."JSON_CARGADO" IS 'Texto del json cargado';
 
   COMMENT ON COLUMN "RECA_DB"."CD_JSON_CARGUE"."NRO_PROPONENTE" IS 'Número de registro de proponente asignado, cuando corresponda a un registro RUP';
 
   COMMENT ON COLUMN "RECA_DB"."CD_JSON_CARGUE"."MATRICULA" IS 'Número de la matrícula asociada al cargue';
--------------------------------------------------------
--  DDL for Table CD_JSON_GENERADO
--------------------------------------------------------

  CREATE TABLE "RECA_DB"."CD_JSON_GENERADO" 
   (	"ID" NUMBER(15,0), 
	"ID_MAESTRA_JSON" NUMBER(15,0), 
	"FECHA_GENERACION" DATE, 
	"JSON_GENERADO" CLOB, 
	"LOG" VARCHAR2(3000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RECADATA" 
 LOB ("JSON_GENERADO") STORE AS BASICFILE (
  TABLESPACE "RECADATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
 

   COMMENT ON COLUMN "RECA_DB"."CD_JSON_GENERADO"."LOG" IS 'Log proceso.';
--------------------------------------------------------
--  DDL for Table CD_JSON_LOG_ERRORES_CARGUE
--------------------------------------------------------

  CREATE TABLE "RECA_DB"."CD_JSON_LOG_ERRORES_CARGUE" 
   (	"ID" NUMBER(15,0), 
	"ERROR" VARCHAR2(4000 BYTE), 
	"CD_JSON_CARGUE_ID" NUMBER(15,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RECADATA" ;
--------------------------------------------------------
--  DDL for Table CD_MAESTRA_JSON
--------------------------------------------------------

  CREATE TABLE "RECA_DB"."CD_MAESTRA_JSON" 
   (	"ID" NUMBER(15,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"DESCRIPCION" VARCHAR2(3000 BYTE), 
	"ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RECADATA" ;
 

   COMMENT ON COLUMN "RECA_DB"."CD_MAESTRA_JSON"."ID" IS 'ID PRINCIPAL TABLA';
 
   COMMENT ON COLUMN "RECA_DB"."CD_MAESTRA_JSON"."NOMBRE" IS 'NOMBRE DEL JSON';
 
   COMMENT ON COLUMN "RECA_DB"."CD_MAESTRA_JSON"."DESCRIPCION" IS 'DESCRIPCION JSON.';
 
   COMMENT ON COLUMN "RECA_DB"."CD_MAESTRA_JSON"."ESTADO" IS 'ESTADO DEL JSON A- ACTIVO - I INACTIVO';
--------------------------------------------------------
--  DDL for Table CD_RELACION_TABLAS_JSON
--------------------------------------------------------

  CREATE TABLE "RECA_DB"."CD_RELACION_TABLAS_JSON" 
   (	"ID" NUMBER(15,0), 
	"ID_TABLA_ESTRUCTURA" NUMBER(15,0), 
	"ID_DETALLE_JSON_RELACION" NUMBER(15,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RECADATA" ;
--------------------------------------------------------
--  DDL for Table CD_TABLA_DATOS_JSON
--------------------------------------------------------

  CREATE TABLE "RECA_DB"."CD_TABLA_DATOS_JSON" 
   (	"ID" NUMBER(15,0), 
	"ID_CD_MAESTRA_JSON" NUMBER(15,0), 
	"ID_DETALLE_JSON" NUMBER(15,0), 
	"VALOR" VARCHAR2(4000 BYTE), 
	"VALORCLOB" CLOB, 
	"CD_JSON_CARGUE_ID" NUMBER(15,0), 
	"NRO_REGISTRO" NUMBER(15,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RECADATA" 
 LOB ("VALORCLOB") STORE AS BASICFILE (
  TABLESPACE "RECADATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
 

   COMMENT ON COLUMN "RECA_DB"."CD_TABLA_DATOS_JSON"."ID" IS 'id principal de la tabla';
 
   COMMENT ON COLUMN "RECA_DB"."CD_TABLA_DATOS_JSON"."ID_CD_MAESTRA_JSON" IS 'id relacion de los maestra json.';
 
   COMMENT ON COLUMN "RECA_DB"."CD_TABLA_DATOS_JSON"."ID_DETALLE_JSON" IS 'id detalle json que define que campo se guardo de la lectua del json.
';
 
   COMMENT ON COLUMN "RECA_DB"."CD_TABLA_DATOS_JSON"."VALOR" IS 'valor del json.';
 
   COMMENT ON COLUMN "RECA_DB"."CD_TABLA_DATOS_JSON"."VALORCLOB" IS 'valor textos largos del json.
';
 
   COMMENT ON COLUMN "RECA_DB"."CD_TABLA_DATOS_JSON"."NRO_REGISTRO" IS 'el numero de registro de los datos a guardar.';
--------------------------------------------------------
--  DDL for Table CD_TABLAS_ESTRUCTURA_JSON
--------------------------------------------------------

  CREATE TABLE "RECA_DB"."CD_TABLAS_ESTRUCTURA_JSON" 
   (	"ID" NUMBER(15,0), 
	"ID_MAESTROJSON" NUMBER(15,0), 
	"TABLA_ORIGEN" VARCHAR2(500 BYTE), 
	"WHERE_DINAMICO" VARCHAR2(4000 BYTE), 
	"TABLA_PADRE" NUMBER(15,0), 
	"TIPO_TABLA" CHAR(1 BYTE), 
	"TAG_TABLA_SINGULAR" VARCHAR2(100 BYTE), 
	"TAG_TABLA_PLURAL" VARCHAR2(100 BYTE), 
	"NOMBRE_PROCESO" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RECADATA" ;
 

   COMMENT ON COLUMN "RECA_DB"."CD_TABLAS_ESTRUCTURA_JSON"."ID" IS 'id llave principal';
 
   COMMENT ON COLUMN "RECA_DB"."CD_TABLAS_ESTRUCTURA_JSON"."ID_MAESTROJSON" IS 'id foranea tabla BAS_MAESTRAJSON';
 
   COMMENT ON COLUMN "RECA_DB"."CD_TABLAS_ESTRUCTURA_JSON"."TABLA_ORIGEN" IS 'Nombre objeto tabla para consultar la inforamcion.';
 
   COMMENT ON COLUMN "RECA_DB"."CD_TABLAS_ESTRUCTURA_JSON"."WHERE_DINAMICO" IS 'where de rabla principal o join de tabla secundaria.';
 
   COMMENT ON COLUMN "RECA_DB"."CD_TABLAS_ESTRUCTURA_JSON"."TABLA_PADRE" IS 'id tabla padre.';
 
   COMMENT ON COLUMN "RECA_DB"."CD_TABLAS_ESTRUCTURA_JSON"."TIPO_TABLA" IS 'P principal ,  S subtabla';
 
   COMMENT ON COLUMN "RECA_DB"."CD_TABLAS_ESTRUCTURA_JSON"."NOMBRE_PROCESO" IS 'Nombre procedimiento';
--------------------------------------------------------
--  DDL for Index BAS_DETALLETABLAJSON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RECA_DB"."BAS_DETALLETABLAJSON_PK" ON "RECA_DB"."CD_DETALLE_TABLA_JSON" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RECADATA" ;
--------------------------------------------------------
--  DDL for Index CD_HOMOLOGACION_JSON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RECA_DB"."CD_HOMOLOGACION_JSON_PK" ON "RECA_DB"."CD_HOMOLOGACION_JSON" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RECADATA" ;
--------------------------------------------------------
--  DDL for Index CD_JSON_CARGUE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RECA_DB"."CD_JSON_CARGUE_PK" ON "RECA_DB"."CD_JSON_CARGUE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RECADATA" ;
--------------------------------------------------------
--  DDL for Index BAS_JSON_GENERADO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RECA_DB"."BAS_JSON_GENERADO_PK" ON "RECA_DB"."CD_JSON_GENERADO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RECADATA" ;
--------------------------------------------------------
--  DDL for Index CD_JSON_LOG_ERRORES_CARGUE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RECA_DB"."CD_JSON_LOG_ERRORES_CARGUE_PK" ON "RECA_DB"."CD_JSON_LOG_ERRORES_CARGUE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RECADATA" ;
--------------------------------------------------------
--  DDL for Index BAS_MAESTRAJSON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RECA_DB"."BAS_MAESTRAJSON_PK" ON "RECA_DB"."CD_MAESTRA_JSON" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RECADATA" ;
--------------------------------------------------------
--  DDL for Index BAS_RELACION_TABLAS_JSON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RECA_DB"."BAS_RELACION_TABLAS_JSON_PK" ON "RECA_DB"."CD_RELACION_TABLAS_JSON" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RECADATA" ;
--------------------------------------------------------
--  DDL for Index CD_TABLA_DATOS_JSON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RECA_DB"."CD_TABLA_DATOS_JSON_PK" ON "RECA_DB"."CD_TABLA_DATOS_JSON" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RECADATA" ;
--------------------------------------------------------
--  DDL for Index BAS_TABLAS_ESTRUCTURA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RECA_DB"."BAS_TABLAS_ESTRUCTURA_PK" ON "RECA_DB"."CD_TABLAS_ESTRUCTURA_JSON" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RECADATA" ;
--------------------------------------------------------
--  Constraints for Table CD_DETALLE_TABLA_JSON
--------------------------------------------------------

  ALTER TABLE "RECA_DB"."CD_DETALLE_TABLA_JSON" ADD CONSTRAINT "BAS_DETALLETABLAJSON_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RECADATA"  ENABLE;
 
  ALTER TABLE "RECA_DB"."CD_DETALLE_TABLA_JSON" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "RECA_DB"."CD_DETALLE_TABLA_JSON" MODIFY ("ID_TABLA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CD_HOMOLOGACION_JSON
--------------------------------------------------------

  ALTER TABLE "RECA_DB"."CD_HOMOLOGACION_JSON" ADD CONSTRAINT "CD_HOMOLOGACION_JSON_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RECADATA"  ENABLE;
 
  ALTER TABLE "RECA_DB"."CD_HOMOLOGACION_JSON" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CD_JSON_CARGUE
--------------------------------------------------------

  ALTER TABLE "RECA_DB"."CD_JSON_CARGUE" ADD CONSTRAINT "CD_JSON_CARGUE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RECADATA"  ENABLE;
 
  ALTER TABLE "RECA_DB"."CD_JSON_CARGUE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "RECA_DB"."CD_JSON_CARGUE" MODIFY ("ID_MAESTRA_JSON" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CD_JSON_GENERADO
--------------------------------------------------------

  ALTER TABLE "RECA_DB"."CD_JSON_GENERADO" ADD CONSTRAINT "BAS_JSON_GENERADO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RECADATA"  ENABLE;
 
  ALTER TABLE "RECA_DB"."CD_JSON_GENERADO" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "RECA_DB"."CD_JSON_GENERADO" MODIFY ("ID_MAESTRA_JSON" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CD_JSON_LOG_ERRORES_CARGUE
--------------------------------------------------------

  ALTER TABLE "RECA_DB"."CD_JSON_LOG_ERRORES_CARGUE" ADD CONSTRAINT "CD_JSON_LOG_ERRORES_CARGUE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RECADATA"  ENABLE;
 
  ALTER TABLE "RECA_DB"."CD_JSON_LOG_ERRORES_CARGUE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CD_MAESTRA_JSON
--------------------------------------------------------

  ALTER TABLE "RECA_DB"."CD_MAESTRA_JSON" ADD CONSTRAINT "BAS_MAESTRAJSON_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RECADATA"  ENABLE;
 
  ALTER TABLE "RECA_DB"."CD_MAESTRA_JSON" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "RECA_DB"."CD_MAESTRA_JSON" ADD CHECK ( estado IN ( 'A', 'I' ) ) ENABLE;
--------------------------------------------------------
--  Constraints for Table CD_RELACION_TABLAS_JSON
--------------------------------------------------------

  ALTER TABLE "RECA_DB"."CD_RELACION_TABLAS_JSON" ADD CONSTRAINT "BAS_RELACION_TABLAS_JSON_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RECADATA"  ENABLE;
 
  ALTER TABLE "RECA_DB"."CD_RELACION_TABLAS_JSON" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "RECA_DB"."CD_RELACION_TABLAS_JSON" MODIFY ("ID_TABLA_ESTRUCTURA" NOT NULL ENABLE);
 
  ALTER TABLE "RECA_DB"."CD_RELACION_TABLAS_JSON" MODIFY ("ID_DETALLE_JSON_RELACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CD_TABLA_DATOS_JSON
--------------------------------------------------------

  ALTER TABLE "RECA_DB"."CD_TABLA_DATOS_JSON" ADD CONSTRAINT "CD_TABLA_DATOS_JSON_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RECADATA"  ENABLE;
 
  ALTER TABLE "RECA_DB"."CD_TABLA_DATOS_JSON" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "RECA_DB"."CD_TABLA_DATOS_JSON" MODIFY ("ID_CD_MAESTRA_JSON" NOT NULL ENABLE);
 
  ALTER TABLE "RECA_DB"."CD_TABLA_DATOS_JSON" MODIFY ("ID_DETALLE_JSON" NOT NULL ENABLE);
 
  ALTER TABLE "RECA_DB"."CD_TABLA_DATOS_JSON" MODIFY ("CD_JSON_CARGUE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CD_TABLAS_ESTRUCTURA_JSON
--------------------------------------------------------

  ALTER TABLE "RECA_DB"."CD_TABLAS_ESTRUCTURA_JSON" ADD CONSTRAINT "BAS_TABLAS_ESTRUCTURA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RECADATA"  ENABLE;
 
  ALTER TABLE "RECA_DB"."CD_TABLAS_ESTRUCTURA_JSON" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "RECA_DB"."CD_TABLAS_ESTRUCTURA_JSON" MODIFY ("ID_MAESTROJSON" NOT NULL ENABLE);
 
  ALTER TABLE "RECA_DB"."CD_TABLAS_ESTRUCTURA_JSON" ADD CONSTRAINT "SYS_C004100719" CHECK (tipo_tabla IN ( 'P', 'S','U' )) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CD_DETALLE_TABLA_JSON
--------------------------------------------------------

  ALTER TABLE "RECA_DB"."CD_DETALLE_TABLA_JSON" ADD CONSTRAINT "TABLA_DETALLE_FK1" FOREIGN KEY ("ID_TABLA")
	  REFERENCES "RECA_DB"."CD_TABLAS_ESTRUCTURA_JSON" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CD_JSON_CARGUE
--------------------------------------------------------

  ALTER TABLE "RECA_DB"."CD_JSON_CARGUE" ADD CONSTRAINT "CD_JSON_CARGUE_FK1" FOREIGN KEY ("ID_MAESTRA_JSON")
	  REFERENCES "RECA_DB"."CD_MAESTRA_JSON" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CD_JSON_GENERADO
--------------------------------------------------------

  ALTER TABLE "RECA_DB"."CD_JSON_GENERADO" ADD CONSTRAINT "CD_JS_GEN_MAESJSON_FK1" FOREIGN KEY ("ID_MAESTRA_JSON")
	  REFERENCES "RECA_DB"."CD_MAESTRA_JSON" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CD_RELACION_TABLAS_JSON
--------------------------------------------------------

  ALTER TABLE "RECA_DB"."CD_RELACION_TABLAS_JSON" ADD CONSTRAINT "CD_REL_TB_FK1" FOREIGN KEY ("ID_DETALLE_JSON_RELACION")
	  REFERENCES "RECA_DB"."CD_DETALLE_TABLA_JSON" ("ID") ENABLE;
 
  ALTER TABLE "RECA_DB"."CD_RELACION_TABLAS_JSON" ADD CONSTRAINT "CD_REL_TB_FK2" FOREIGN KEY ("ID_TABLA_ESTRUCTURA")
	  REFERENCES "RECA_DB"."CD_TABLAS_ESTRUCTURA_JSON" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CD_TABLA_DATOS_JSON
--------------------------------------------------------

  ALTER TABLE "RECA_DB"."CD_TABLA_DATOS_JSON" ADD CONSTRAINT "CD_TABLA_DATOS_FK1" FOREIGN KEY ("ID_CD_MAESTRA_JSON")
	  REFERENCES "RECA_DB"."CD_MAESTRA_JSON" ("ID") ENABLE;
 
  ALTER TABLE "RECA_DB"."CD_TABLA_DATOS_JSON" ADD CONSTRAINT "CD_TABLA_DATOS_JSON_FK2" FOREIGN KEY ("ID_DETALLE_JSON")
	  REFERENCES "RECA_DB"."CD_DETALLE_TABLA_JSON" ("ID") ENABLE;
 
  ALTER TABLE "RECA_DB"."CD_TABLA_DATOS_JSON" ADD CONSTRAINT "CD_TABLA_DATOS_JSON_FK3" FOREIGN KEY ("CD_JSON_CARGUE_ID")
	  REFERENCES "RECA_DB"."CD_JSON_CARGUE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CD_TABLAS_ESTRUCTURA_JSON
--------------------------------------------------------

  ALTER TABLE "RECA_DB"."CD_TABLAS_ESTRUCTURA_JSON" ADD CONSTRAINT "CD_JSONM_TABLAS_FK1" FOREIGN KEY ("ID_MAESTROJSON")
	  REFERENCES "RECA_DB"."CD_MAESTRA_JSON" ("ID") ENABLE;
