DECLARE
  JSONID NUMBER;
  DATOS VARCHAR2(200);
  IDJSONGEN NUMBER;
  CLOBJSONGEN CLOB;
BEGIN
  JSONID := 2;
  DATOS := ' and a.registro = 352 and rownum = 1 ';

  PKG_CD_JSON.GENERARJSON(
    JSONID => JSONID,
    DATOS => DATOS,
    IDJSONGEN => IDJSONGEN,
    CLOBJSONGEN => CLOBJSONGEN
  );
--DBMS_OUTPUT.PUT_LINE('IDJSONGEN = ' || IDJSONGEN);

--DBMS_OUTPUT.PUT_LINE('CLOBJSONGEN = ' || CLOBJSONGEN);

END;



DECLARE
  JSONID NUMBER;
  DATOS VARCHAR2(200);
  IDJSONGEN NUMBER;
  CLOBJSONGEN CLOB;
BEGIN
  JSONID := 1;
  DATOS := ' and i.matricula = 45020 and i.camara = 5 ';

  PKG_CD_JSON.GENERARJSON(
    JSONID => JSONID,
    DATOS => DATOS,
    IDJSONGEN => IDJSONGEN,
    CLOBJSONGEN => CLOBJSONGEN
  );
--DBMS_OUTPUT.PUT_LINE('IDJSONGEN = ' || IDJSONGEN);

--DBMS_OUTPUT.PUT_LINE('CLOBJSONGEN = ' || CLOBJSONGEN);

END;




DECLARE
  VPROCESO NUMBER;
BEGIN
  VPROCESO := 165;

  PKG_CD_CAMBIO_DOM.CARGATABLA(
    VPROCESO => VPROCESO
  );
  /*commit;
  exception 
  when others then 
   dbms_output.put_line(sqlerrm);
  rollback;
  */
END;
