DECLARE
  JSONID NUMBER;
  DATOS VARCHAR2(200);
  IDJSONGEN NUMBER;
  CLOBJSONGEN CLOB;
BEGIN
  JSONID := 2;
  DATOS := ' and a.registro = 352 and rownum = 1 ';

  PKG_CD_JSON.GENERARJSON(
    JSONID => JSONID,
    DATOS => DATOS,
    IDJSONGEN => IDJSONGEN,
    CLOBJSONGEN => CLOBJSONGEN
  );
--DBMS_OUTPUT.PUT_LINE('IDJSONGEN = ' || IDJSONGEN);

--DBMS_OUTPUT.PUT_LINE('CLOBJSONGEN = ' || CLOBJSONGEN);

END;



DECLARE
  JSONID NUMBER;
  DATOS VARCHAR2(200);
  IDJSONGEN NUMBER;
  CLOBJSONGEN CLOB;
BEGIN
  JSONID := 1;
  DATOS := ' and i.matricula = 1296 and i.camara = 5 ';

  PKG_CD_JSON.GENERARJSON(
    JSONID => JSONID,
    DATOS => DATOS,
    IDJSONGEN => IDJSONGEN,
    CLOBJSONGEN => CLOBJSONGEN
  );
--DBMS_OUTPUT.PUT_LINE('IDJSONGEN = ' || IDJSONGEN);

--DBMS_OUTPUT.PUT_LINE('CLOBJSONGEN = ' || CLOBJSONGEN);

END;




DECLARE
  VPROCESO NUMBER;
BEGIN
  VPROCESO := 210;

  PKG_CD_CAMBIO_DOM.CARGATABLA(
    VPROCESO => VPROCESO
  );
  /*commit;
  exception 
  when others then 
   dbms_output.put_line(sqlerrm);
  rollback;
  */
END;

SELECT * FROM INSCRITOS
WHERE MATRICULA =904533
--- GENERAR JSON A PIE. 

DECLARE
  IDPROCESO VARCHAR2(200);
  CADENA VARCHAR2(200);
  USUARIO VARCHAR2(200);
  CLAVE VARCHAR2(200);
  v_Return VARCHAR2(200);
BEGIN
  IDPROCESO := 210;
  CADENA := 'jdbc:oracle:thin:@172.16.1.58:1521:CAMARA';
  USUARIO := 'RECA_DB';
  CLAVE := 'RECA';

  v_Return := PKG_CD_JSON.CARGARJSON(
    IDPROCESO => IDPROCESO,
    CADENA => CADENA,
    USUARIO => USUARIO,
    CLAVE => CLAVE
  );

DBMS_OUTPUT.PUT_LINE('v_Return = ' || v_Return);
 
  
--rollback; 
END;
TRUNCATE TABLE CD_TABLA_DATOS_JSON


select * from IMPRESION_LIBROS_COMERCIALES
PK_IMPRESION_LIBROS_COMERCIALE


select * from IMPRESION_LIBROS_COMERCIALES
where matricula = 452199